name: Fotograf Maria Pries
favicon: null
layout_spectrum: 0.9661727941129357
typography_spectrum: 0.09039028803817928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7430820511654019
  lightness: 0.18916882970370352
  saturation: 0.7864929153583944
  rhythmicContrast: 0.47057420993223786
purpose: []
